- name: download goss.
  become: yes
  uri:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ arch_map[ansible_architecture] }}"
    dest: "{{ goss_binary }}"
    mode: '755'
    status_code:
      - 200
      - 304
  tags:
    - goss

# - name: enable executable permissions
#   file:
#     path: "{{ goss_binary }}"
#     mode: 0755

- name: upload goss test file
  template: src={{ goss_tmpl }}  dest={{ goss_file }}
  when: goss_tmpl is defined and goss_tmpl is not none
  tags:
    - goss

- name: write goss test file
  copy:
    content: "{{ goss_payload | to_nice_yaml(indent=2) }}"
    dest: "{{ goss_file }}"
  when: goss_payload is defined and goss_payload is not none
  tags:
    - goss

- name: test goss file
  goss:
    path: "{{ goss_file }}"
    goss_path: "{{ goss_binary }}"
  tags:
    - goss
